Renew remote proxies with clean environment
```
 error: myproxy-logon: /data/srv/TaskManager/3.3.13.rc3/slc6_amd64_gcc481/external/condor/8.3.1-comp/lib/condor/libglobus_common.so.0: no version information available (required by myproxy-logon)
myproxy-logon: /data/srv/TaskManager/3.3.13.rc3/slc6_amd64_gcc481/external/condor/8.3.1-comp/lib/condor/libglobus_common.so.0: no version information available (required by /usr/lib64/libmyproxy.so.6)

```